# Generated by Django 2.2 on 2020-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200630_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingEmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('request_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRecoveryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('request_id', models.CharField(max_length=255)),
            ],
        ),
    ]
