# Generated by Django 2.2 on 2020-08-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_outstandingemailconfirmation_passwordrecoveryrequest'),
        ('app', '0003_faqcategory_faqitem'),
    ]

    operations = [
    ]
