# Generated by Django 2.2 on 2020-09-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20200812_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='about_page_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='about_page_text',
            field=models.TextField(default='...'),
            preserve_default=False,
        ),
    ]
