# Generated by Django 2.2 on 2020-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200903_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='shop_address',
            field=models.TextField(default='...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='shop_alternate_telephone',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='shop_email',
            field=models.EmailField(default='test@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='shop_telephone',
            field=models.CharField(default='123456', max_length=254),
            preserve_default=False,
        ),
    ]
