# Generated by Django 2.2 on 2020-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200619_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='show_in_navigation',
            field=models.BooleanField(default=True),
        ),
    ]
