# Generated by Django 2.2 on 2020-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='about_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='about_info',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
