# Generated by Django 2.2 on 2020-09-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200831_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='secondary_currency',
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency'),
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=12, max_digits=16)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Currency')),
                ('to_currrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_currency', to='app.Currency')),
            ],
        ),
    ]
