# Generated by Django 2.2 on 2020-06-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_department_show_in_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
