# Generated by Django 2.2 on 2020-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200904_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='shop_gps',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
