# Generated by Django 2.2 on 2020-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200620_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo')], max_length=64)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZWL', 'ZWL')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='appsettings',
            name='base_currency',
            field=models.CharField(default='USD', max_length=16),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='secondary_currency',
            field=models.CharField(default='ZWL', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZWL', 'ZWL')], default='USD', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('order', 'order'), ('paid', 'paid'), ('processing', 'processing'), ('shipped', 'shipped'), ('received', 'received')], default='cart', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=14.5, max_digits=24),
        ),
    ]
