# Generated by Django 2.2 on 2020-09-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200908_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='base_currency',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='to_currrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='app.Currency'),
        ),
    ]
