# Generated by Django 2.2 on 2020-09-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200908_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyexchange',
            old_name='to_currrency',
            new_name='to_currency',
        ),
    ]
