# Generated by Django 2.2 on 2020-06-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_rank',
            field=models.IntegerField(default=0),
        ),
    ]
