# Generated by Django 2.2 on 2020-09-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appsettings_shop_gps'),
        ('app', '0009_auto_20200912_0909'),
    ]

    operations = [
    ]
