# Generated by Django 2.2 on 2020-09-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20200914_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='about_info',
        ),
    ]
