# Generated by Django 2.2 on 2020-09-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200929_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name_plural': 'AppSettings'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyexchange',
            options={'verbose_name_plural': 'Currency Exchange'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name_plural': 'Faq Categories'},
        ),
    ]
